# Generated by Django 5.1.1 on 2024-10-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.TextField(max_length=4)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.TextField()),
                ('funeral_home_name', models.CharField(max_length=255)),
                ('place_of_death', models.CharField(choices=[('home', 'Home'), ('hospital', 'Hospital'), ('other', 'Other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('license_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('doctor', 'Doctor'), ('pathologist', 'Pathologist')], max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('branch', models.CharField(default='Lusaka', max_length=100)),
                ('NRC', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('branch', models.CharField(default='Lusaka', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_disposal', models.CharField(choices=[('buried', 'Buried'), ('cremated', 'Cremated'), ('other', 'Other')], max_length=50)),
                ('site_of_disposal', models.CharField(max_length=255)),
                ('funeral_home_name', models.CharField(max_length=255)),
                ('date_of_disposal', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='members.deceased')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disposals', to='members.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('date_issued', models.DateField()),
                ('certificate_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.deceased')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Embalmer',
            fields=[
                ('license_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('embalming_details', models.TextField()),
                ('date_of_embalming', models.DateField()),
                ('nrc', models.CharField(max_length=100, unique=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.deceased')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship_to_deceased', models.CharField(max_length=100)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='members.deceased')),
            ],
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('date_conducted', models.DateField()),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.deceased')),
                ('pathologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pathologist')),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.deceased')),
                ('disposal_permit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.disposal')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
            ],
            options={
                'unique_together': {('deceased', 'doctor')},
            },
        ),
    ]
